-- Function to handle new user creation
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.family_members (
    id,
    email,
    full_name,
    age,
    family_branch,
    employment_status,
    marital_status,
    graduate_status,
    location,
    address,
    phone_number,
    photo_url
  )
  values (
    new.id,
    new.email,
    new.raw_user_meta_data->>'full_name',
    (new.raw_user_meta_data->>'age')::int,
    new.raw_user_meta_data->>'family_branch',
    new.raw_user_meta_data->>'employment_status',
    new.raw_user_meta_data->>'marital_status',
    new.raw_user_meta_data->>'graduate_status',
    new.raw_user_meta_data->>'location',
    new.raw_user_meta_data->>'address',
    new.raw_user_meta_data->>'phone_number',
    new.raw_user_meta_data->>'photo_url'
  );
  return new;
end;
$$ language plpgsql security definer;

-- Trigger to call the function on new user creation
create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ============================================
-- Row Level Security (RLS) Policies
-- ============================================

-- Enable RLS on family_members table
alter table public.family_members enable row level security;

-- Policy: Users can read all family members
create policy "Family members are viewable by authenticated users"
  on public.family_members for select
  to authenticated
  using (true);

-- Policy: Users can update their own profile
create policy "Users can update their own profile"
  on public.family_members for update
  to authenticated
  using (auth.uid() = id);

-- Policy: Users can insert their own profile (via trigger)
create policy "Users can insert their own profile"
  on public.family_members for insert
  to authenticated
  with check (auth.uid() = id);

-- ============================================
-- Activity Log Table
-- ============================================

create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  action text not null,
  table_name text not null,
  record_id uuid,
  old_values jsonb,
  new_values jsonb,
  created_at timestamptz default now()
);

-- Enable RLS on activity_log
alter table public.activity_log enable row level security;

-- Policy: Users can read their own activity
create policy "Users can view their own activity"
  on public.activity_log for select
  to authenticated
  using (auth.uid() = user_id);

-- Policy: Service role can insert activity
create policy "Service role can insert activity"
  on public.activity_log for insert
  to authenticated
  with check (auth.uid() = user_id);

-- Function to log activity
create or replace function public.log_activity(
  p_user_id uuid,
  p_action text,
  p_table_name text,
  p_record_id uuid default null,
  p_old_values jsonb default null,
  p_new_values jsonb default null
)
returns void as $$
begin
  insert into public.activity_log (user_id, action, table_name, record_id, old_values, new_values)
  values (p_user_id, p_action, p_table_name, p_record_id, p_old_values, p_new_values);
end;
$$ language plpgsql security definer;
